version: '3.9'
name: marketmoogleapi
services:
  database:
    image: 'postgres:alpine'
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${DB_NAME}
    secrets:
      - db_user
      - db_password
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    networks:
      - db_network
  MarketMoogle:
    image: 'golang:1.21-alpine'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: 'marketmoogle-profit'
    environment:
      SECRETS_DIR: /run/secrets/
      DB_HOST: 'database'
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    secrets:
      - db_user
      - db_password
      - xiv_api_key
      - universalis_api_key
    depends_on:
      - 'database'
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
    networks:
      - db_network

volumes:
  database:

secrets:
  db_user:
    file: secrets/db_user.txt
  db_password:
    file: secrets/db_password.txt
  xiv_api_key:
    file: secrets/xiv_api_key.txt
  universalis_api_key:
    file: secrets/universalis_api_key.txt
    
networks:
  db_network:
    driver: bridge