version: '3.7'

services:
  mongodb:
    image: 'mongo:latest'
    volumes:
      - mongodb:/data/database
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'access123!'
    ports:
      - '27017:27017'
    expose:
      - '27017'
  marketmoogleapi:
    build: .
    image: 'golang:latest'
    container_name: 'marketmoogle'
    restart: 'always'
    environment:
      API_PORT: '8080'
      MONGO_PORT: '27017'
      MONGO_HOST: 'mongodb'
      MONGO_DBNAME: 'sanctuary'
      XIV_API_KEY: 'd52759a79b3b42d68b80a3948c084fc517650dfcda5242358265ee0f8267c934'
      UNIVERSALIS_API_KEY: 'd52759a79b3b42d68b80a3948c084fc517650dfcda5242358265ee0f8267c934'
    depends_on:
      - "mongodb"
    ports:
      - '8080:8080'
    expose:
      - '8080'
    
volumes:
  mongodb: