version: '3.7'

services:
  database:
    image: 'postgres:alpine'
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${DB_NAME}
    secrets:
      - db_user
      - db_password
    ports:
      - '5432:5432'
    expose:
      - '5432'
  marketmoogleapi:
    image: 'golang:latest'
    build: .
    env_file:
      - .env
    container_name: 'marketmoogle-api'
    command: air ./server.go -b 0.0.0.0
    environment:
      DB_PORT: '5432'
      DB_USER: /run/secrets/db_user
      DB_PASSWORD: /run/secrets/db_password
      DB_NAME: ${DB_NAME}
      XIV_API_KEY: /run/secrets/xiv_api_key
      UNIVERSALIS_API_KEY: /run/secrets/universalis_api_key
    secrets:
      - db_user
      - db_password
      - xiv_api_key
      - universalis_api_key
    depends_on:
      - 'database'
    ports:
      - '3000:3000'
    expose:
      - '3000'
    
volumes:
  database:
    
secrets:
  db_user:
    file: secrets/db_user.txt
  db_password:
    file: secrets/db_password.txt
  xiv_api_key:
    file: secrets/xiv_api_key.txt
  universalis_api_key:
    file: secrets/universalis_api_key.txt