version: '3.7'

services:
  mongodb:
    image: 'mongo:latest'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'access123!'
    ports:
      - '27017:27017'
    expose:
      - '27017'
  sanctuaryapi:
    build: .
    image: 'golang:latest'
    container_name: 'sanctuary'
    restart: 'always'
    environment:
      MONGO_PORT: '8080'
      MONGO_HOST: 'mongodb'
    depends_on:
      - "mongodb"
    ports:
      - '8080:8080'
    expose:
      - '8080'
    
volumes:
  mongodb: