/*
 * Copyright (c) 2022 Carl Alexander Bird.
 * This file (itemrecipes.go) is part of MarketMoogle and is released GNU General Public License.
 * Please see the "LICENSE" file within MarketMoogle to view the full license. This file, and all code within MarketMoogle fall under the GNU General Public License.
 */

package xivapi

type T struct {
	ALC         interface{} `json:"ALC"`
	ALCTarget   string      `json:"ALCTarget"`
	ALCTargetID int         `json:"ALCTargetID"`
	ARM         interface{} `json:"ARM"`
	ARMTarget   string      `json:"ARMTarget"`
	ARMTargetID int         `json:"ARMTargetID"`
	BSM         interface{} `json:"BSM"`
	BSMTarget   string      `json:"BSMTarget"`
	BSMTargetID int         `json:"BSMTargetID"`
	CRP         interface{} `json:"CRP"`
	CRPTarget   string      `json:"CRPTarget"`
	CRPTargetID int         `json:"CRPTargetID"`
	CUL         interface{} `json:"CUL"`
	CULTarget   string      `json:"CULTarget"`
	CULTargetID int         `json:"CULTargetID"`
	GSM         struct {
		AmountIngredient0 int `json:"AmountIngredient0"`
		AmountIngredient1 int `json:"AmountIngredient1"`
		AmountIngredient2 int `json:"AmountIngredient2"`
		AmountIngredient3 int `json:"AmountIngredient3"`
		AmountIngredient4 int `json:"AmountIngredient4"`
		AmountIngredient5 int `json:"AmountIngredient5"`
		AmountIngredient6 int `json:"AmountIngredient6"`
		AmountIngredient7 int `json:"AmountIngredient7"`
		AmountIngredient8 int `json:"AmountIngredient8"`
		AmountIngredient9 int `json:"AmountIngredient9"`
		AmountResult      int `json:"AmountResult"`
		CanHq             int `json:"CanHq"`
		CanQuickSynth     int `json:"CanQuickSynth"`
		CraftType         struct {
			ID           int    `json:"ID"`
			MainPhysical int    `json:"MainPhysical"`
			Name         string `json:"Name"`
			NameDe       string `json:"Name_de"`
			NameEn       string `json:"Name_en"`
			NameFr       string `json:"Name_fr"`
			NameJa       string `json:"Name_ja"`
			SubPhysical  int    `json:"SubPhysical"`
		} `json:"CraftType"`
		CraftTypeTarget          string      `json:"CraftTypeTarget"`
		CraftTypeTargetID        int         `json:"CraftTypeTargetID"`
		DifficultyFactor         int         `json:"DifficultyFactor"`
		DurabilityFactor         int         `json:"DurabilityFactor"`
		ExpRewarded              int         `json:"ExpRewarded"`
		ID                       int         `json:"ID"`
		IsExpert                 int         `json:"IsExpert"`
		IsSecondary              int         `json:"IsSecondary"`
		IsSpecializationRequired int         `json:"IsSpecializationRequired"`
		ItemIngredient0          GameItem    `json:"ItemIngredient0"`
		ItemIngredient0Target    string      `json:"ItemIngredient0Target"`
		ItemIngredient0TargetID  int         `json:"ItemIngredient0TargetID"`
		ItemIngredient1          GameItem    `json:"ItemIngredient1"`
		ItemIngredient1Target    string      `json:"ItemIngredient1Target"`
		ItemIngredient1TargetID  int         `json:"ItemIngredient1TargetID"`
		ItemIngredient2          GameItem    `json:"ItemIngredient2"`
		ItemIngredient2Target    string      `json:"ItemIngredient2Target"`
		ItemIngredient2TargetID  int         `json:"ItemIngredient2TargetID"`
		ItemIngredient3          GameItem    `json:"ItemIngredient3"`
		ItemIngredient3Target    string      `json:"ItemIngredient3Target"`
		ItemIngredient3TargetID  int         `json:"ItemIngredient3TargetID"`
		ItemIngredient4          GameItem    `json:"ItemIngredient4"`
		ItemIngredient4Target    string      `json:"ItemIngredient4Target"`
		ItemIngredient4TargetID  int         `json:"ItemIngredient4TargetID"`
		ItemIngredient5          GameItem    `json:"ItemIngredient5"`
		ItemIngredient5Target    string      `json:"ItemIngredient5Target"`
		ItemIngredient5TargetID  int         `json:"ItemIngredient5TargetID"`
		ItemIngredient6          GameItem    `json:"ItemIngredient6"`
		ItemIngredient6Target    string      `json:"ItemIngredient6Target"`
		ItemIngredient6TargetID  int         `json:"ItemIngredient6TargetID"`
		ItemIngredient7          GameItem    `json:"ItemIngredient7"`
		ItemIngredient7Target    string      `json:"ItemIngredient7Target"`
		ItemIngredient7TargetID  int         `json:"ItemIngredient7TargetID"`
		ItemIngredient8          GameItem    `json:"ItemIngredient8"`
		ItemIngredient8Target    string      `json:"ItemIngredient8Target"`
		ItemIngredient8TargetID  int         `json:"ItemIngredient8TargetID"`
		ItemIngredient9          GameItem    `json:"ItemIngredient9"`
		ItemIngredient9Target    string      `json:"ItemIngredient9Target"`
		ItemIngredient9TargetID  string      `json:"ItemIngredient9TargetID"`
		ItemRequired             GameItem    `json:"ItemRequired"`
		ItemRequiredTarget       string      `json:"ItemRequiredTarget"`
		ItemRequiredTargetID     int         `json:"ItemRequiredTargetID"`
		ItemResult               GameItem    `json:"ItemResult"`
		ItemResultTarget         string      `json:"ItemResultTarget"`
		ItemResultTargetID       int         `json:"ItemResultTargetID"`
		MaterialQualityFactor    int         `json:"MaterialQualityFactor"`
		Number                   int         `json:"Number"`
		PatchNumber              int         `json:"PatchNumber"`
		QualityFactor            int         `json:"QualityFactor"`
		Quest                    interface{} `json:"Quest"`
		QuestTarget              string      `json:"QuestTarget"`
		QuestTargetID            int         `json:"QuestTargetID"`
		QuickSynthControl        int         `json:"QuickSynthControl"`
		QuickSynthCraftsmanship  int         `json:"QuickSynthCraftsmanship"`
		RecipeLevelTable         struct {
			ClassJobLevel          int `json:"ClassJobLevel"`
			ConditionsFlag         int `json:"ConditionsFlag"`
			Difficulty             int `json:"Difficulty"`
			Durability             int `json:"Durability"`
			ID                     int `json:"ID"`
			ProgressDivider        int `json:"ProgressDivider"`
			ProgressModifier       int `json:"ProgressModifier"`
			Quality                int `json:"Quality"`
			QualityDivider         int `json:"QualityDivider"`
			QualityModifier        int `json:"QualityModifier"`
			Stars                  int `json:"Stars"`
			SuggestedControl       int `json:"SuggestedControl"`
			SuggestedCraftsmanship int `json:"SuggestedCraftsmanship"`
		} `json:"RecipeLevelTable"`
		RecipeLevelTableTarget   string      `json:"RecipeLevelTableTarget"`
		RecipeLevelTableTargetID int         `json:"RecipeLevelTableTargetID"`
		RequiredControl          int         `json:"RequiredControl"`
		RequiredCraftsmanship    int         `json:"RequiredCraftsmanship"`
		SecretRecipeBook         interface{} `json:"SecretRecipeBook"`
		SecretRecipeBookTarget   string      `json:"SecretRecipeBookTarget"`
		SecretRecipeBookTargetID int         `json:"SecretRecipeBookTargetID"`
		StatusRequired           interface{} `json:"StatusRequired"`
		StatusRequiredTarget     string      `json:"StatusRequiredTarget"`
		StatusRequiredTargetID   int         `json:"StatusRequiredTargetID"`
	} `json:"GSM"`
	GSMTarget        string        `json:"GSMTargetID"`
	GSMTargetID      int           `json:"GSMTargetID"`
	GameContentLinks []interface{} `json:"GameContentLinks"`
	GamePatch        struct {
		Banner       interface{} `json:"Banner"`
		ExName       string      `json:"ExName"`
		ExVersion    int         `json:"ExVersion"`
		ID           int         `json:"ID"`
		IsExpansion  bool        `json:"IsExpansion"`
		Name         string      `json:"Name"`
		NameCn       string      `json:"Name_cn"`
		NameDe       string      `json:"Name_de"`
		NameEn       string      `json:"Name_en"`
		NameFr       string      `json:"Name_fr"`
		NameJa       string      `json:"Name_ja"`
		NameKr       string      `json:"Name_kr"`
		PatchNotes   string      `json:"PatchNotes"`
		PatchNotesDe string      `json:"PatchNotes_de"`
		PatchNotesEn string      `json:"PatchNotes_en"`
		PatchNotesFr string      `json:"PatchNotes_fr"`
		PatchNotesJa string      `json:"PatchNotes_ja"`
		ReleaseDate  int         `json:"ReleaseDate"`
		Url          string      `json:"Url"`
		Version      string      `json:"Version"`
	} `json:"GamePatch"`
	ID          int         `json:"ID"`
	LTW         interface{} `json:"LTW"`
	LTWTarget   string      `json:"LTWTarget"`
	LTWTargetID int         `json:"LTWTargetID"`
	Patch       int         `json:"Patch"`
	Url         string      `json:"Url"`
	WVR         interface{} `json:"WVR"`
	WVRTarget   string      `json:"WVRTarget"`
	WVRTargetID int         `json:"WVRTargetID"`
}
